dnsdock:
  image: tonistiigi/dnsdock
  volumes:
    - /var/run/docker.sock:/run/docker.sock
  ports:
    - 172.17.42.1:53:53/udp
mongors1n1:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db
  environment:
    TERM: xterm
  hostname: rs1n1
  domainname: mongocluster.com
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongors1n1:/data/db
mongors1n2:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongors1n2:/data/db
mongors1n3:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --replSet mongors1 --dbpath /data/db
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongors1n3:/data/db
mongors2n1:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongors2n1:/data/db
mongors2n2:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongors2n2:/data/db
mongors2n3:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --replSet mongors2 --dbpath /data/db
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongors2n3:/data/db
mongocfg1:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongo-cfg-1:/data/db
mongocfg2:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongo-cfg-2:/data/db
mongocfg3:
  image: mongo:3.1
  command: mongod --noprealloc --smallfiles --dbpath /data/db --configsvr
  environment:
    TERM: xterm
  dns:
    - 172.17.42.1
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data/mongo-cfg-3:/data/db
